name: Entrega continua

on:
  workflow_call:

jobs:

  ECS:
    runs-on: ubuntu-latest
    steps:

    - name: Configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Obtendo arquivo da tarefa
      run: |
        aws ecs describe-task-definition --task-definition Tarefa_API-GO --query taskDefinition > task-definition-orig.json
        jq 'del(.enableFaultInjection)' task-definition-orig.json > task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: Go
        image: guilherme2907/go_ci:latest
        environment-variables: |
                    DB_HOST=${{ secrets.REMOTE_DB_HOST }}
                    DB_USER=${{ secrets.REMOTE_DB_USER }}
                    DB_PASSWORD=${{ secrets.REMOTE_DB_PASSWORD }}
                    DB_DBNAME=${{ secrets.DB_NAME }}
                    DB_DBPORT=${{ secrets.DB_PORT }}
                    PORT=8000

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: Servico_APIGo
        cluster: API-Go-Cluster
        wait-for-service-stability: true

                     